### PR TITLE
Go example

### PR DESCRIPTION
**Pull request by PeterWinzell**
Go example added. Subscription to a time can signal, publishing result on the web.

### CODE REVIEW

**Comment by AleksandarFilipov** [comment]
@PeterWinzell thanks a lot, I'll try and help out getting some examples running.

**Comment by AleksandarFilipov** [comment]
You need to help me understand how to get it running.
I try the following
```
go get -u google.golang.org/grpc
```
then i do
```
go run main.go
```
without success, please help me understand, now with go ;)

**Comment by petervolvowinz** [comment]
So **go run main.go pngprint.go** should work to start the app. There's a plotting sever app that produces a png av the time based signal , so you need to start that as well and you will get a png out put at 9000, go run plotterserver2.go.

However, the example needs the time based can frame:
func subsignalDB() (*settings){
	data := &settings{
		Namespaces: []spaces{
			{Name: "BodyCANhs",
				Frames: []framee{
					{Frameid: "CEMBodyFr29",
						Sigids: []signalid{
							{Identifier: "Yr"},
							{Identifier: "Mth"},
							{Identifier: "Day"},
							{Identifier: "Hr"},
							{Identifier: "Mins"},
							{Identifier: "Sec"},
							{Identifier: "TiAndDateIndcn_UB"},
							{Identifier: "TiAndDateVld"},
						}},
				},
			},
		},
	}

So this needs to be matched for the example to work...I don't know how to get that into the fake dbc.

**Comment by AleksandarFilipov** [comment]
Ok so if you are good with my changes i also suggest that we add the relevant identifiers as Day/Mth and so forth in https://github.com/volvo-cars/signalbroker-server/blob/master/configuration/human/benchc.json (as opposed to changing your code) then then the example will be runnable as is on any machine (including your mac :). Then if we throw on some random data it will display some random numbers.
Unless you are able to do it ahead of me i'll fix it next week. Many thanks!

**Pull request merged**
